name: Core

on:
  push:
    paths: [packages/core/**]
  pull_request:
    paths: [packages/core/**]

permissions: read-all

jobs:
  check:
    defaults:
      run:
        working-directory: packages/core

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install
        working-directory: ./

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
