name: Frontend

on:
  push:
    paths: [packages/core/**, packages/hooks/**, packages/frontend/**]
  pull_request:
    paths: [packages/core/**, packages/hooks/**, packages/frontend/**]

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        working-directory: packages/frontend

      - name: Build
        run: yarn g:build
